services:
  mongo:
    image: mongo
    ports:
     - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./mongo/1_docker-mongo-init.js:/docker-entrypoint-initdb.d/1_mongo-init.js
      - ${ADDITIONAL_SCRIPT:-/dev/null}:/docker-entrypoint-initdb.d/script.js
