name: Deployment pipeline

on:
  push:
    branches:
      - master

env:
  TEST_MONGODB_URI: mongodb://the_username:the_password@localhost:3456/test_db

jobs:
  deployment_pipeline:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./back-end
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: npm install 
        run: npm install  
      - name: lint
        run: npm run lint
      - name: docker db
        run: docker-compose up -d
      - name: test
        run: npm run test
      - name: deploy
        working-directory: ./back-end
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip')}}
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "sleepy-atoll-34773"
          heroku_email: "quinalayojason@gmail.com"
          healthcheck: "https://sleepy-atoll-34773.herokuapp.com/healthcheck"
          checkstring: "ok"
          rollbackonhealthcheckfailed: true